context:
  version: "2.6.0"

package:
  name: golangci-lint
  version: ${{ version }}

source:
  url: https://github.com/golangci/golangci-lint/archive/v${{ version }}.tar.gz
  sha256: 262ec6f58ebaad58656d311905c867a78b14152221d35c5680e53297b03019bf

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - golangci-lint --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Stricter gofmt
  homepage: https://golangci-lint.run
  repository: https://github.com/golangci/golangci-lint

extra:
  recipe-maintainers:
    - danielnachun
