context:
  version: "2.6.2"

package:
  name: golangci-lint
  version: ${{ version }}

source:
  url: https://github.com/golangci/golangci-lint/archive/v${{ version }}.tar.gz
  sha256: 2cbe6b01858780ecc28b69840fe9621dabdb6287a50d96f186e491b682b4cbd5

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - golangci-lint --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Stricter gofmt
  homepage: https://golangci-lint.run
  repository: https://github.com/golangci/golangci-lint

extra:
  recipe-maintainers:
    - danielnachun
