context:
  version: "2.11.4"

package:
  name: golangci-lint
  version: ${{ version }}

source:
  url: https://github.com/golangci/golangci-lint/archive/v${{ version }}.tar.gz
  sha256: 388dc80d6bd01417144c2bad2b21f58fc069f66bb91f63c111b5e826e67d240a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - golangci-lint --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Stricter gofmt
  homepage: https://golangci-lint.run
  repository: https://github.com/golangci/golangci-lint

extra:
  recipe-maintainers:
    - danielnachun
