context:
  version: 2.5.0

package:
  name: golangci-lint
  version: ${{ version }}

source:
  url: https://github.com/golangci/golangci-lint/archive/v${{ version }}.tar.gz
  sha256: 0e0fcb42d9eda9ab0ff167c1df1e79cfe6aac72fbc9f97b9ff158c96baa438f4

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - golangci-lint --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Stricter gofmt
  homepage: https://golangci-lint.run
  repository: https://github.com/golangci/golangci-lint

extra:
  recipe-maintainers:
    - danielnachun
